name: Scrape

on:
  push:
    branches:
      - 'main'
    paths:
      - 'scraper/**/*'
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  ualberta:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Scrape data
      run: npm run scrape

    - name: Update data
      run: |
        git config --global user.name 'Steven Tang'
        git config --global user.email '18170455+steventango@users.noreply.github.com'
        git add data
        git diff-index --quiet HEAD || git commit -m "Update UAlberta data"
        git push

    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.txt
